version: "3"
services:
  monopoly-mongodb:
    image: mongo
    expose:
      - "27017"
    networks:
      - monopoly
  monopoly-web:
    image: jass921026/monopoly
    expose:
      - "2022"
    depends_on:
      - monopoly-mongodb
    environment:
      MONGO_URL: mongodb://monopoly-mongodb/monopoly
      WEB_DOMAIN: eecamp-monopoly.ntuee.org
    tty: true
    stdin_open: true
    networks:
      - monopoly
      - nginx

networks:
  nginx:
    external: true
  monopoly:
